apiVersion: apps/v1
kind: Deployment
metadata:
  name: v1
  labels:
    app: nginx
spec:
  replicas: 7
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest # Corrected from 'niginx'
          ports:
            - containerPort: 80
