apiVersion: v1
kind: Service
metadata:
  name: local-dev-service
spec:
  type: NodePort
  selector:
    app: local-dev
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30100 # We will need to map this in kind.yml
