apiVersion: v1
kind: Pod
metadata:
  name: local-dev-test
  labels:
    app: local-dev
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: app-volume
      mountPath: /usr/share/nginx/html # Mount into nginx's web root
  volumes:
  - name: app-volume
    hostPath:
      path: /app-data # This path is from inside the node (defined in kind.yml)
      type: Directory
